import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { RepositoryOrderByWithRelationInputObjectSchema as RepositoryOrderByWithRelationInputObjectSchema } from './objects/RepositoryOrderByWithRelationInput.schema';
import { RepositoryWhereInputObjectSchema as RepositoryWhereInputObjectSchema } from './objects/RepositoryWhereInput.schema';
import { RepositoryWhereUniqueInputObjectSchema as RepositoryWhereUniqueInputObjectSchema } from './objects/RepositoryWhereUniqueInput.schema';
import { RepositoryCountAggregateInputObjectSchema as RepositoryCountAggregateInputObjectSchema } from './objects/RepositoryCountAggregateInput.schema';
import { RepositoryMinAggregateInputObjectSchema as RepositoryMinAggregateInputObjectSchema } from './objects/RepositoryMinAggregateInput.schema';
import { RepositoryMaxAggregateInputObjectSchema as RepositoryMaxAggregateInputObjectSchema } from './objects/RepositoryMaxAggregateInput.schema';

export const RepositoryAggregateSchema: z.ZodType<Prisma.RepositoryAggregateArgs> = z.object({ orderBy: z.union([RepositoryOrderByWithRelationInputObjectSchema, RepositoryOrderByWithRelationInputObjectSchema.array()]).optional(), where: RepositoryWhereInputObjectSchema.optional(), cursor: RepositoryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), RepositoryCountAggregateInputObjectSchema ]).optional(), _min: RepositoryMinAggregateInputObjectSchema.optional(), _max: RepositoryMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.RepositoryAggregateArgs>;

export const RepositoryAggregateZodSchema = z.object({ orderBy: z.union([RepositoryOrderByWithRelationInputObjectSchema, RepositoryOrderByWithRelationInputObjectSchema.array()]).optional(), where: RepositoryWhereInputObjectSchema.optional(), cursor: RepositoryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), RepositoryCountAggregateInputObjectSchema ]).optional(), _min: RepositoryMinAggregateInputObjectSchema.optional(), _max: RepositoryMaxAggregateInputObjectSchema.optional() }).strict();