import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { RoadmapProjectWhereInputObjectSchema as RoadmapProjectWhereInputObjectSchema } from './objects/RoadmapProjectWhereInput.schema';
import { RoadmapProjectOrderByWithAggregationInputObjectSchema as RoadmapProjectOrderByWithAggregationInputObjectSchema } from './objects/RoadmapProjectOrderByWithAggregationInput.schema';
import { RoadmapProjectScalarWhereWithAggregatesInputObjectSchema as RoadmapProjectScalarWhereWithAggregatesInputObjectSchema } from './objects/RoadmapProjectScalarWhereWithAggregatesInput.schema';
import { RoadmapProjectScalarFieldEnumSchema } from './enums/RoadmapProjectScalarFieldEnum.schema';
import { RoadmapProjectCountAggregateInputObjectSchema as RoadmapProjectCountAggregateInputObjectSchema } from './objects/RoadmapProjectCountAggregateInput.schema';
import { RoadmapProjectMinAggregateInputObjectSchema as RoadmapProjectMinAggregateInputObjectSchema } from './objects/RoadmapProjectMinAggregateInput.schema';
import { RoadmapProjectMaxAggregateInputObjectSchema as RoadmapProjectMaxAggregateInputObjectSchema } from './objects/RoadmapProjectMaxAggregateInput.schema';
import { RoadmapProjectAvgAggregateInputObjectSchema as RoadmapProjectAvgAggregateInputObjectSchema } from './objects/RoadmapProjectAvgAggregateInput.schema';
import { RoadmapProjectSumAggregateInputObjectSchema as RoadmapProjectSumAggregateInputObjectSchema } from './objects/RoadmapProjectSumAggregateInput.schema';

export const RoadmapProjectGroupBySchema: z.ZodType<Prisma.RoadmapProjectGroupByArgs> = z.object({ where: RoadmapProjectWhereInputObjectSchema.optional(), orderBy: z.union([RoadmapProjectOrderByWithAggregationInputObjectSchema, RoadmapProjectOrderByWithAggregationInputObjectSchema.array()]).optional(), having: RoadmapProjectScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RoadmapProjectScalarFieldEnumSchema), _count: z.union([ z.literal(true), RoadmapProjectCountAggregateInputObjectSchema ]).optional(), _min: RoadmapProjectMinAggregateInputObjectSchema.optional(), _max: RoadmapProjectMaxAggregateInputObjectSchema.optional(), _avg: RoadmapProjectAvgAggregateInputObjectSchema.optional(), _sum: RoadmapProjectSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.RoadmapProjectGroupByArgs>;

export const RoadmapProjectGroupByZodSchema = z.object({ where: RoadmapProjectWhereInputObjectSchema.optional(), orderBy: z.union([RoadmapProjectOrderByWithAggregationInputObjectSchema, RoadmapProjectOrderByWithAggregationInputObjectSchema.array()]).optional(), having: RoadmapProjectScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(RoadmapProjectScalarFieldEnumSchema), _count: z.union([ z.literal(true), RoadmapProjectCountAggregateInputObjectSchema ]).optional(), _min: RoadmapProjectMinAggregateInputObjectSchema.optional(), _max: RoadmapProjectMaxAggregateInputObjectSchema.optional(), _avg: RoadmapProjectAvgAggregateInputObjectSchema.optional(), _sum: RoadmapProjectSumAggregateInputObjectSchema.optional() }).strict();